version: "3.9"

services:
  gofiber:
    container_name: gofiber
    image: cosmtrek/air
    working_dir: /root/app
    volumes:
      - ./aliases.bashrc:/root/.bashrc
      - .:/root/app
      - /root/app/tmp
      - /root/app/prisma/db
      - /go
    ports:
      - 9090:3000
    tty: true
    environment:
      - TZ=Asia/Bangkok
    restart: always