version: "3.9"

services:
  gofiber:
    container_name: gofiber
    image: cosmtrek/air
    working_dir: /root/app
    volumes:
      - gofiber:/root/app
      - ./aliases.bashrc:/root/.bashrc
    ports:
      - 9090:3000
    tty: true
    environment:
      - TZ=Asia/Bangkok
    #restart: always

volumes:
  gofiber:
 # Define synchronization and forwarding sessions
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
        paths:
          - tmp
          - db
          - .*
          - '*.command'
          - docker*
          - Dockerfile
    gofiber:
      alpha: .
      beta: volume://gofiber
